Repository kebblar/petstore-front, pull requests merged in 2021-06, with the labels that each got.

#27 Feature/vimpollos carrito compras
  src/Header.vue
  src/assets/bicho3.jpg
  src/assets/empty-cart.svg
  src/components/Carrito.vue
  src/components/CompraConfirmada.vue
  src/components/DetallePago.vue
Labels: vimpollos

#26 Fix/administracion compras
  src/components/AdministracionCompras.vue
Labels: vimpollos

#28 Integración de anuncios
  jenkins.sh
  package.json
  src/components/ConsultaAnunciosPublico.vue
  src/components/DetalleProducto.vue
  src/components/admin/Anuncio.vue
  src/components/admin/ConsultaAnuncio.vue
  src/components/admin/Imagen.vue
  src/router/index.js
Labels: Equipo Azul

#43 Fix/imagen principal fechas
  src/components/admin/Anuncio.vue
  src/components/admin/Imagen.vue
Labels: Equipo Azul

#49 Validación de caracteres especiales
  src/components/Registro.vue
Labels: bug

#54 Mejoras diseño y funciones de anuncios
  src/components/ConsultaAnunciosPublico.vue
  src/components/DetalleProducto.vue
  src/components/Inicio.vue
  src/components/admin/ConsultaAnuncio.vue
  src/router/index.js
Labels: Equipo Azul

#65 Modificacion de etiqueta Precio por Precio máximo
  src/components/ConsultaAnunciosPublico.vue
Labels: Equipo Azul
